apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    "backstage.io/kubernetes-id": dice-roller
    "backstage.io/kubernetes-namespace": default
    "argocd/app-name": dice-roller
    github.com/project-slug: 'RoadieHQ/sample-service'
spec:
  type: service
  lifecycle: production
  owner: guest

